name: meteread

services:
  meteread:
    container_name: meteread
    hostname: meteread
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      INFLUXDB_URL: http://influxdb:8181
    command:
      - read
      - raw

  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: influxdb:3-core
    user: root
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
      - --without-auth
    volumes:
      - influxdb-data:/var/lib/influxdb3/data
      - influxdb-plugins:/var/lib/influxdb3/plugins

volumes:
  influxdb-data:
  influxdb-plugins:
