[project]
name = "meteread"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dsmr-parser>=1.4.3",
    "influxdb-client>=1.36",
    "typer>=0.19.2",
]

[dependency-groups]
dev = ["pytest>=8"]

[tool.pytest.ini_options]
log_level = "INFO"
